package types

import (
	"github.com/cosmos/cosmos-sdk/types/errors"
)

// errors
var (
	ErrSetPermissions             = errors.Register(ModuleName, 2, "error setting permissions")
	ErrEmptyProposerAccAddress    = errors.Register(ModuleName, 3, "empty proposer key")
	ErrEmptyPermissionsAccAddress = errors.Register(ModuleName, 4, "empty address to set the permissions")
	ErrNotEnoughPermissions       = errors.Register(ModuleName, 5, "not enough permissions")
	ErrCouncilorEmptyAddress      = errors.Register(ModuleName, 6, "empty councilor address")
	ErrRoleDoesNotExist           = errors.Register(ModuleName, 7, "role does not exist")
	ErrWhitelisting               = errors.Register(ModuleName, 8, "error adding to whitelist")
	ErrEmptyPermissions           = errors.Register(ModuleName, 9, "empty permissions")
	ErrRoleExist                  = errors.Register(ModuleName, 12, "role already exist")
	ErrRoleAlreadyAssigned        = errors.Register(ModuleName, 13, "role already assigned")
	ErrRoleNotAssigned            = errors.Register(ModuleName, 14, "role not assigned")
	ErrCouncilorNotFound          = errors.Register(ModuleName, 15, "councilor not found")
	ErrCouncilorNotPaused         = errors.Register(ModuleName, 16, "councilor not paused")
	ErrCouncilorJailed            = errors.Register(ModuleName, 17, "councilor jailed")
	ErrCouncilorInactivated       = errors.Register(ModuleName, 18, "councilor inactivated")
	ErrCouncilorPaused            = errors.Register(ModuleName, 19, "councilor paused")
	ErrProposalDoesNotExist       = errors.Register(ModuleName, 20, "proposal does not exist")
	ErrActorIsNotActive           = errors.Register(ModuleName, 21, "actor is not active")
	ErrInvalidNetworkProperty     = errors.Register(ModuleName, 22, "invalid network property")
	ErrFeeNotExist                = errors.Register(ModuleName, 23, "fee does not exist")
	ErrPoorNetworkMessagesNotSet  = errors.Register(ModuleName, 24, "poor network messages not set")
	ErrGettingProposals           = errors.Register(ModuleName, 25, "error getting proposals")
	ErrGettingProposalVotes       = errors.Register(ModuleName, 26, "error getting votes for proposal")
	ErrVotingTimeEnded            = errors.Register(ModuleName, 27, "voting time has ended")
	ErrInvalidDate                = errors.Register(ModuleName, 28, "invalid date")
	ErrEmptyVerifierAccAddress    = errors.Register(ModuleName, 29, "empty verifier account address")
	ErrInvalidRecordId            = errors.Register(ModuleName, 30, "invalid record id")
	ErrInvalidVerifyRequestId     = errors.Register(ModuleName, 31, "invalid verify request id")
	ErrInvalidTip                 = errors.Register(ModuleName, 32, "invalid tip")
	ErrInvalidRecordIds           = errors.Register(ModuleName, 33, "invalid record ids")
	ErrEmptyInfos                 = errors.Register(ModuleName, 34, "invalid record ids")
	ErrUnknownProposal            = errors.Register(ModuleName, 35, "unknown proposal")
	ErrInactiveProposal           = errors.Register(ModuleName, 36, "inactive proposal")
	ErrAlreadyActiveProposal      = errors.Register(ModuleName, 37, "proposal already active")
	ErrInvalidProposalContent     = errors.Register(ModuleName, 38, "invalid proposal content")
	ErrInvalidProposalType        = errors.Register(ModuleName, 39, "invalid proposal type")
	ErrInvalidVote                = errors.Register(ModuleName, 40, "invalid vote option")
	ErrInvalidGenesis             = errors.Register(ModuleName, 41, "invalid genesis state")
	ErrNoProposalHandlerExists    = errors.Register(ModuleName, 42, "no handler exists for proposal type")
	ErrInvalidIdentityRecordKey   = errors.Register(ModuleName, 43, "invalid identity record key")
	ErrMonikerDeletionNotAllowed  = errors.Register(ModuleName, 44, "moniker field is not allowed to delete")
	ErrInvalidIdentityRecordId    = errors.Register(ModuleName, 45, "invalid identity record id")
	ErrInvalidApprovalTip         = errors.Register(ModuleName, 46, "invalid approval tip")
	ErrKeyShouldBeUnique          = errors.Register(ModuleName, 47, "key should be unique")
	ErrInvalidRoleSid             = errors.Register(ModuleName, 48, "invalid role sid")
	ErrInvalidRoleIdentifier      = errors.Register(ModuleName, 49, "invalid role identifier")
)
