// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kira/recovery/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryRecoveryRecordRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryRecoveryRecordRequest) Reset()         { *m = QueryRecoveryRecordRequest{} }
func (m *QueryRecoveryRecordRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRecoveryRecordRequest) ProtoMessage()    {}
func (*QueryRecoveryRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ccd2ab45d9acb75, []int{0}
}
func (m *QueryRecoveryRecordRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRecoveryRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRecoveryRecordRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRecoveryRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRecoveryRecordRequest.Merge(m, src)
}
func (m *QueryRecoveryRecordRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRecoveryRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRecoveryRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRecoveryRecordRequest proto.InternalMessageInfo

func (m *QueryRecoveryRecordRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryRecoveryRecordResponse struct {
	Record RecoveryRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record"`
}

func (m *QueryRecoveryRecordResponse) Reset()         { *m = QueryRecoveryRecordResponse{} }
func (m *QueryRecoveryRecordResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRecoveryRecordResponse) ProtoMessage()    {}
func (*QueryRecoveryRecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ccd2ab45d9acb75, []int{1}
}
func (m *QueryRecoveryRecordResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRecoveryRecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRecoveryRecordResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRecoveryRecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRecoveryRecordResponse.Merge(m, src)
}
func (m *QueryRecoveryRecordResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRecoveryRecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRecoveryRecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRecoveryRecordResponse proto.InternalMessageInfo

func (m *QueryRecoveryRecordResponse) GetRecord() RecoveryRecord {
	if m != nil {
		return m.Record
	}
	return RecoveryRecord{}
}

type QueryRecoveryTokenRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryRecoveryTokenRequest) Reset()         { *m = QueryRecoveryTokenRequest{} }
func (m *QueryRecoveryTokenRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRecoveryTokenRequest) ProtoMessage()    {}
func (*QueryRecoveryTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ccd2ab45d9acb75, []int{2}
}
func (m *QueryRecoveryTokenRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRecoveryTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRecoveryTokenRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRecoveryTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRecoveryTokenRequest.Merge(m, src)
}
func (m *QueryRecoveryTokenRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRecoveryTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRecoveryTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRecoveryTokenRequest proto.InternalMessageInfo

func (m *QueryRecoveryTokenRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryRecoveryTokenResponse struct {
	Token RecoveryToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token"`
}

func (m *QueryRecoveryTokenResponse) Reset()         { *m = QueryRecoveryTokenResponse{} }
func (m *QueryRecoveryTokenResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRecoveryTokenResponse) ProtoMessage()    {}
func (*QueryRecoveryTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ccd2ab45d9acb75, []int{3}
}
func (m *QueryRecoveryTokenResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRecoveryTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRecoveryTokenResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRecoveryTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRecoveryTokenResponse.Merge(m, src)
}
func (m *QueryRecoveryTokenResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRecoveryTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRecoveryTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRecoveryTokenResponse proto.InternalMessageInfo

func (m *QueryRecoveryTokenResponse) GetToken() RecoveryToken {
	if m != nil {
		return m.Token
	}
	return RecoveryToken{}
}

func init() {
	proto.RegisterType((*QueryRecoveryRecordRequest)(nil), "kira.recovery.QueryRecoveryRecordRequest")
	proto.RegisterType((*QueryRecoveryRecordResponse)(nil), "kira.recovery.QueryRecoveryRecordResponse")
	proto.RegisterType((*QueryRecoveryTokenRequest)(nil), "kira.recovery.QueryRecoveryTokenRequest")
	proto.RegisterType((*QueryRecoveryTokenResponse)(nil), "kira.recovery.QueryRecoveryTokenResponse")
}

func init() { proto.RegisterFile("kira/recovery/query.proto", fileDescriptor_1ccd2ab45d9acb75) }

var fileDescriptor_1ccd2ab45d9acb75 = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x41, 0x4f, 0xe2, 0x40,
	0x14, 0xc7, 0x5b, 0xb2, 0xb0, 0xd9, 0xd9, 0xb0, 0x87, 0xc9, 0x1e, 0xa0, 0xcb, 0x76, 0x37, 0x3d,
	0x01, 0x87, 0xce, 0xc2, 0x46, 0x25, 0xf1, 0x86, 0xde, 0x3c, 0xd9, 0x18, 0x0f, 0x5c, 0xcc, 0x14,
	0xc6, 0xda, 0x20, 0x9d, 0x32, 0x33, 0x25, 0x12, 0xe3, 0xc5, 0x4f, 0x60, 0xe2, 0xd9, 0x83, 0xdf,
	0x86, 0xc4, 0x0b, 0x89, 0x17, 0x4f, 0xc6, 0x80, 0x1f, 0xc4, 0x74, 0x3a, 0x0d, 0x96, 0x88, 0x70,
	0xea, 0x9b, 0xf7, 0xde, 0xff, 0xbd, 0xdf, 0xfc, 0x3b, 0xa0, 0xdc, 0xf7, 0x19, 0x46, 0x8c, 0x74,
	0xe9, 0x88, 0xb0, 0x31, 0x1a, 0x46, 0x84, 0x8d, 0xed, 0x90, 0x51, 0x41, 0x61, 0x31, 0x2e, 0xd9,
	0x69, 0xc9, 0xa8, 0x77, 0x29, 0x1f, 0x50, 0x8e, 0x5c, 0xcc, 0x49, 0xd2, 0x87, 0x46, 0x0d, 0x97,
	0x08, 0xdc, 0x40, 0x21, 0xf6, 0xfc, 0x00, 0x0b, 0x9f, 0x06, 0x89, 0xd4, 0xf8, 0xe9, 0x51, 0x8f,
	0xca, 0x10, 0xc5, 0x91, 0xca, 0x96, 0x3d, 0x4a, 0xbd, 0x73, 0x82, 0xe4, 0xc9, 0x8d, 0x4e, 0x11,
	0x0e, 0xd4, 0x2e, 0xa3, 0xa2, 0x4a, 0x38, 0xf4, 0x11, 0x0e, 0x02, 0x2a, 0xe4, 0x34, 0x9e, 0x56,
	0xb3, 0x90, 0x69, 0x90, 0x54, 0xad, 0x6d, 0x60, 0x1c, 0xc6, 0x38, 0x8e, 0x4a, 0xc7, 0x5f, 0xd6,
	0x73, 0xc8, 0x30, 0x22, 0x5c, 0xc0, 0x12, 0xf8, 0x8a, 0x7b, 0x3d, 0x46, 0x38, 0x2f, 0xe9, 0x7f,
	0xf5, 0xea, 0x37, 0x27, 0x3d, 0x5a, 0x1d, 0xf0, 0xeb, 0x43, 0x1d, 0x0f, 0x69, 0xc0, 0x09, 0xdc,
	0x05, 0x05, 0x26, 0x33, 0x52, 0xf7, 0xbd, 0xf9, 0xdb, 0xce, 0xf8, 0x61, 0x67, 0x65, 0xed, 0x2f,
	0x93, 0xe7, 0x3f, 0x9a, 0xa3, 0x24, 0xd6, 0x16, 0x28, 0x67, 0x66, 0x1f, 0xd1, 0x3e, 0x09, 0xd6,
	0x23, 0x1d, 0x2f, 0x5d, 0x45, 0xc9, 0x14, 0x51, 0x0b, 0xe4, 0x45, 0x9c, 0x50, 0x40, 0x95, 0x15,
	0x40, 0x52, 0xa4, 0x78, 0x12, 0x41, 0xf3, 0x21, 0x07, 0xf2, 0x72, 0x30, 0xbc, 0xd7, 0xc1, 0x8f,
	0x2c, 0x39, 0xac, 0x2d, 0xcd, 0x59, 0x6d, 0xa6, 0x51, 0xdf, 0xa4, 0x35, 0xa1, 0xb5, 0x5a, 0xd7,
	0x8f, 0xaf, 0xb7, 0xb9, 0x26, 0xfc, 0x87, 0xb2, 0x7f, 0x2f, 0x7d, 0x34, 0x69, 0xe2, 0x24, 0xb1,
	0x0c, 0x5d, 0x2a, 0x13, 0xae, 0xe0, 0x9d, 0x0e, 0x8a, 0x99, 0xcb, 0xc0, 0xea, 0x67, 0x7b, 0xdf,
	0x7b, 0x6b, 0xd4, 0x36, 0xe8, 0x54, 0x80, 0x3b, 0x12, 0xb0, 0x01, 0xd1, 0x3a, 0x40, 0xe9, 0xe1,
	0x82, 0xaf, 0xbd, 0x3f, 0x99, 0x99, 0xfa, 0x74, 0x66, 0xea, 0x2f, 0x33, 0x53, 0xbf, 0x99, 0x9b,
	0xda, 0x74, 0x6e, 0x6a, 0x4f, 0x73, 0x53, 0xeb, 0xd4, 0x3d, 0x5f, 0x9c, 0x45, 0xae, 0xdd, 0xa5,
	0x03, 0x74, 0xe0, 0x33, 0xbc, 0x47, 0x19, 0x41, 0x9c, 0xf4, 0xb1, 0x8f, 0x2e, 0x16, 0x0b, 0xc4,
	0x38, 0x24, 0xdc, 0x2d, 0xc8, 0xd7, 0xfb, 0xff, 0x2d, 0x00, 0x00, 0xff, 0xff, 0x01, 0x88, 0xa6,
	0x8e, 0x82, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// given KIRA public address as parameter return data from the recovery registrar
	RecoveryRecord(ctx context.Context, in *QueryRecoveryRecordRequest, opts ...grpc.CallOption) (*QueryRecoveryRecordResponse, error)
	RecoveryToken(ctx context.Context, in *QueryRecoveryTokenRequest, opts ...grpc.CallOption) (*QueryRecoveryTokenResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) RecoveryRecord(ctx context.Context, in *QueryRecoveryRecordRequest, opts ...grpc.CallOption) (*QueryRecoveryRecordResponse, error) {
	out := new(QueryRecoveryRecordResponse)
	err := c.cc.Invoke(ctx, "/kira.recovery.Query/RecoveryRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RecoveryToken(ctx context.Context, in *QueryRecoveryTokenRequest, opts ...grpc.CallOption) (*QueryRecoveryTokenResponse, error) {
	out := new(QueryRecoveryTokenResponse)
	err := c.cc.Invoke(ctx, "/kira.recovery.Query/RecoveryToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// given KIRA public address as parameter return data from the recovery registrar
	RecoveryRecord(context.Context, *QueryRecoveryRecordRequest) (*QueryRecoveryRecordResponse, error)
	RecoveryToken(context.Context, *QueryRecoveryTokenRequest) (*QueryRecoveryTokenResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) RecoveryRecord(ctx context.Context, req *QueryRecoveryRecordRequest) (*QueryRecoveryRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecoveryRecord not implemented")
}
func (*UnimplementedQueryServer) RecoveryToken(ctx context.Context, req *QueryRecoveryTokenRequest) (*QueryRecoveryTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecoveryToken not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_RecoveryRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRecoveryRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RecoveryRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kira.recovery.Query/RecoveryRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RecoveryRecord(ctx, req.(*QueryRecoveryRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RecoveryToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRecoveryTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RecoveryToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kira.recovery.Query/RecoveryToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RecoveryToken(ctx, req.(*QueryRecoveryTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kira.recovery.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecoveryRecord",
			Handler:    _Query_RecoveryRecord_Handler,
		},
		{
			MethodName: "RecoveryToken",
			Handler:    _Query_RecoveryToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kira/recovery/query.proto",
}

func (m *QueryRecoveryRecordRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRecoveryRecordRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRecoveryRecordRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRecoveryRecordResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRecoveryRecordResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRecoveryRecordResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Record.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryRecoveryTokenRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRecoveryTokenRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRecoveryTokenRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRecoveryTokenResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRecoveryTokenResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRecoveryTokenResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Token.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryRecoveryRecordRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRecoveryRecordResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Record.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryRecoveryTokenRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRecoveryTokenResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Token.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryRecoveryRecordRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRecoveryRecordRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRecoveryRecordRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRecoveryRecordResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRecoveryRecordResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRecoveryRecordResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Record", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Record.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRecoveryTokenRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRecoveryTokenRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRecoveryTokenRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRecoveryTokenResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRecoveryTokenResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRecoveryTokenResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Token.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
