// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kira/spending/pool.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/cosmos/gogoproto/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ClaimInfo struct {
	Account   string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	PoolName  string `protobuf:"bytes,2,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"`
	LastClaim uint64 `protobuf:"varint,3,opt,name=last_claim,json=lastClaim,proto3" json:"last_claim,omitempty"`
}

func (m *ClaimInfo) Reset()         { *m = ClaimInfo{} }
func (m *ClaimInfo) String() string { return proto.CompactTextString(m) }
func (*ClaimInfo) ProtoMessage()    {}
func (*ClaimInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6027931ab19c9a21, []int{0}
}
func (m *ClaimInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClaimInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClaimInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClaimInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClaimInfo.Merge(m, src)
}
func (m *ClaimInfo) XXX_Size() int {
	return m.Size()
}
func (m *ClaimInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClaimInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClaimInfo proto.InternalMessageInfo

func (m *ClaimInfo) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *ClaimInfo) GetPoolName() string {
	if m != nil {
		return m.PoolName
	}
	return ""
}

func (m *ClaimInfo) GetLastClaim() uint64 {
	if m != nil {
		return m.LastClaim
	}
	return 0
}

type PermInfo struct {
	OwnerRoles    []uint64 `protobuf:"varint,1,rep,packed,name=owner_roles,json=ownerRoles,proto3" json:"owner_roles,omitempty"`
	OwnerAccounts []string `protobuf:"bytes,2,rep,name=owner_accounts,json=ownerAccounts,proto3" json:"owner_accounts,omitempty"`
}

func (m *PermInfo) Reset()         { *m = PermInfo{} }
func (m *PermInfo) String() string { return proto.CompactTextString(m) }
func (*PermInfo) ProtoMessage()    {}
func (*PermInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6027931ab19c9a21, []int{1}
}
func (m *PermInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PermInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PermInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PermInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermInfo.Merge(m, src)
}
func (m *PermInfo) XXX_Size() int {
	return m.Size()
}
func (m *PermInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PermInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PermInfo proto.InternalMessageInfo

func (m *PermInfo) GetOwnerRoles() []uint64 {
	if m != nil {
		return m.OwnerRoles
	}
	return nil
}

func (m *PermInfo) GetOwnerAccounts() []string {
	if m != nil {
		return m.OwnerAccounts
	}
	return nil
}

type WeightedRole struct {
	Role   uint64                                 `protobuf:"varint,1,opt,name=role,proto3" json:"role,omitempty"`
	Weight github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=weight,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"weight"`
}

func (m *WeightedRole) Reset()         { *m = WeightedRole{} }
func (m *WeightedRole) String() string { return proto.CompactTextString(m) }
func (*WeightedRole) ProtoMessage()    {}
func (*WeightedRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_6027931ab19c9a21, []int{2}
}
func (m *WeightedRole) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WeightedRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WeightedRole.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WeightedRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeightedRole.Merge(m, src)
}
func (m *WeightedRole) XXX_Size() int {
	return m.Size()
}
func (m *WeightedRole) XXX_DiscardUnknown() {
	xxx_messageInfo_WeightedRole.DiscardUnknown(m)
}

var xxx_messageInfo_WeightedRole proto.InternalMessageInfo

func (m *WeightedRole) GetRole() uint64 {
	if m != nil {
		return m.Role
	}
	return 0
}

type WeightedAccount struct {
	Account string                                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Weight  github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=weight,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"weight"`
}

func (m *WeightedAccount) Reset()         { *m = WeightedAccount{} }
func (m *WeightedAccount) String() string { return proto.CompactTextString(m) }
func (*WeightedAccount) ProtoMessage()    {}
func (*WeightedAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_6027931ab19c9a21, []int{3}
}
func (m *WeightedAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WeightedAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WeightedAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WeightedAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeightedAccount.Merge(m, src)
}
func (m *WeightedAccount) XXX_Size() int {
	return m.Size()
}
func (m *WeightedAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_WeightedAccount.DiscardUnknown(m)
}

var xxx_messageInfo_WeightedAccount proto.InternalMessageInfo

func (m *WeightedAccount) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type WeightedPermInfo struct {
	Roles    []WeightedRole    `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles"`
	Accounts []WeightedAccount `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts"`
}

func (m *WeightedPermInfo) Reset()         { *m = WeightedPermInfo{} }
func (m *WeightedPermInfo) String() string { return proto.CompactTextString(m) }
func (*WeightedPermInfo) ProtoMessage()    {}
func (*WeightedPermInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6027931ab19c9a21, []int{4}
}
func (m *WeightedPermInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WeightedPermInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WeightedPermInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WeightedPermInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeightedPermInfo.Merge(m, src)
}
func (m *WeightedPermInfo) XXX_Size() int {
	return m.Size()
}
func (m *WeightedPermInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WeightedPermInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WeightedPermInfo proto.InternalMessageInfo

func (m *WeightedPermInfo) GetRoles() []WeightedRole {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *WeightedPermInfo) GetAccounts() []WeightedAccount {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type SpendingPool struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// claim-start & claim-end - defines the exact time period (Unix timestamps) between which tokens can be claimed from the pool, allowing for a precise funds distribution.
	ClaimStart  uint64 `protobuf:"varint,2,opt,name=claim_start,json=claimStart,proto3" json:"claim_start,omitempty"`
	ClaimEnd    uint64 `protobuf:"varint,3,opt,name=claim_end,json=claimEnd,proto3" json:"claim_end,omitempty"`
	ClaimExpiry uint64 `protobuf:"varint,4,opt,name=claim_expiry,json=claimExpiry,proto3" json:"claim_expiry,omitempty"`
	// rate of distribution in the smallest token denomination per 1 second (this value can be a float number, smaller than actual denomination)
	Rates []github_com_cosmos_cosmos_sdk_types.DecCoin `protobuf:"bytes,5,rep,name=rates,proto3,customtype=github.com/cosmos/cosmos-sdk/types.DecCoin" json:"rates" yaml:"rates"`
	// pool specific % of owner accounts that must vote YES or NO for any of the pool proposals to be valid.
	VoteQuorum github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,6,opt,name=vote_quorum,json=voteQuorum,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"vote_quorum"`
	// period of time in seconds that any of the pool proposals must last before passing or being rejected
	VotePeriod uint64 `protobuf:"varint,7,opt,name=vote_period,json=votePeriod,proto3" json:"vote_period,omitempty"`
	// period of time that must pass before any of the pool proposal is enacted
	VoteEnactment uint64 `protobuf:"varint,8,opt,name=vote_enactment,json=voteEnactment,proto3" json:"vote_enactment,omitempty"`
	// defines a list of accounts/roles controlling the spending pool via “governance-like” proposals
	Owners *PermInfo `protobuf:"bytes,9,opt,name=owners,proto3" json:"owners,omitempty"`
	// defines set of accounts/roles to which funds can be distributed
	Beneficiaries           *WeightedPermInfo                         `protobuf:"bytes,10,opt,name=beneficiaries,proto3" json:"beneficiaries,omitempty"`
	Balances                []github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,11,rep,name=balances,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"balances"`
	DynamicRate             bool                                      `protobuf:"varint,12,opt,name=dynamic_rate,json=dynamicRate,proto3" json:"dynamic_rate,omitempty"`
	DynamicRatePeriod       uint64                                    `protobuf:"varint,13,opt,name=dynamic_rate_period,json=dynamicRatePeriod,proto3" json:"dynamic_rate_period,omitempty"`
	LastDynamicRateCalcTime uint64                                    `protobuf:"varint,14,opt,name=last_dynamic_rate_calc_time,json=lastDynamicRateCalcTime,proto3" json:"last_dynamic_rate_calc_time,omitempty"`
}

func (m *SpendingPool) Reset()         { *m = SpendingPool{} }
func (m *SpendingPool) String() string { return proto.CompactTextString(m) }
func (*SpendingPool) ProtoMessage()    {}
func (*SpendingPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_6027931ab19c9a21, []int{5}
}
func (m *SpendingPool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SpendingPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SpendingPool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SpendingPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpendingPool.Merge(m, src)
}
func (m *SpendingPool) XXX_Size() int {
	return m.Size()
}
func (m *SpendingPool) XXX_DiscardUnknown() {
	xxx_messageInfo_SpendingPool.DiscardUnknown(m)
}

var xxx_messageInfo_SpendingPool proto.InternalMessageInfo

func (m *SpendingPool) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SpendingPool) GetClaimStart() uint64 {
	if m != nil {
		return m.ClaimStart
	}
	return 0
}

func (m *SpendingPool) GetClaimEnd() uint64 {
	if m != nil {
		return m.ClaimEnd
	}
	return 0
}

func (m *SpendingPool) GetClaimExpiry() uint64 {
	if m != nil {
		return m.ClaimExpiry
	}
	return 0
}

func (m *SpendingPool) GetVotePeriod() uint64 {
	if m != nil {
		return m.VotePeriod
	}
	return 0
}

func (m *SpendingPool) GetVoteEnactment() uint64 {
	if m != nil {
		return m.VoteEnactment
	}
	return 0
}

func (m *SpendingPool) GetOwners() *PermInfo {
	if m != nil {
		return m.Owners
	}
	return nil
}

func (m *SpendingPool) GetBeneficiaries() *WeightedPermInfo {
	if m != nil {
		return m.Beneficiaries
	}
	return nil
}

func (m *SpendingPool) GetDynamicRate() bool {
	if m != nil {
		return m.DynamicRate
	}
	return false
}

func (m *SpendingPool) GetDynamicRatePeriod() uint64 {
	if m != nil {
		return m.DynamicRatePeriod
	}
	return 0
}

func (m *SpendingPool) GetLastDynamicRateCalcTime() uint64 {
	if m != nil {
		return m.LastDynamicRateCalcTime
	}
	return 0
}

func init() {
	proto.RegisterType((*ClaimInfo)(nil), "kira.spending.ClaimInfo")
	proto.RegisterType((*PermInfo)(nil), "kira.spending.PermInfo")
	proto.RegisterType((*WeightedRole)(nil), "kira.spending.WeightedRole")
	proto.RegisterType((*WeightedAccount)(nil), "kira.spending.WeightedAccount")
	proto.RegisterType((*WeightedPermInfo)(nil), "kira.spending.WeightedPermInfo")
	proto.RegisterType((*SpendingPool)(nil), "kira.spending.SpendingPool")
}

func init() { proto.RegisterFile("kira/spending/pool.proto", fileDescriptor_6027931ab19c9a21) }

var fileDescriptor_6027931ab19c9a21 = []byte{
	// 723 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x51, 0x6b, 0x13, 0x4b,
	0x14, 0xce, 0xb6, 0x9b, 0x34, 0x39, 0x49, 0x7a, 0xef, 0x9d, 0x7b, 0xa1, 0x43, 0xcb, 0x4d, 0x62,
	0x40, 0x0d, 0x82, 0xbb, 0x50, 0x1f, 0x84, 0xe2, 0x83, 0x26, 0x8d, 0x20, 0x05, 0xad, 0x5b, 0xc1,
	0xe2, 0x4b, 0x98, 0x6c, 0xa6, 0xe9, 0xd0, 0xdd, 0x9d, 0x75, 0x67, 0x63, 0x9b, 0x7f, 0x21, 0xf8,
	0x07, 0xfc, 0x39, 0x7d, 0xf0, 0xa1, 0x8f, 0xe2, 0x43, 0x91, 0xf6, 0xc5, 0x67, 0x7f, 0x81, 0xcc,
	0xd9, 0xd9, 0x34, 0x11, 0x2a, 0x45, 0x7c, 0xea, 0xf4, 0x3b, 0xdf, 0xf7, 0x9d, 0xc9, 0x77, 0xce,
	0x0e, 0xd0, 0x23, 0x91, 0x30, 0x57, 0xc5, 0x3c, 0x1a, 0x89, 0x68, 0xec, 0xc6, 0x52, 0x06, 0x4e,
	0x9c, 0xc8, 0x54, 0x92, 0xba, 0xae, 0x38, 0x79, 0x65, 0xbd, 0x39, 0x96, 0x72, 0x1c, 0x70, 0x17,
	0x8b, 0xc3, 0xc9, 0x81, 0x9b, 0x8a, 0x90, 0xab, 0x94, 0x85, 0x71, 0xc6, 0x5f, 0xff, 0x6f, 0x2c,
	0xc7, 0x12, 0x8f, 0xae, 0x3e, 0x65, 0x68, 0x9b, 0x41, 0xa5, 0x17, 0x30, 0x11, 0x3e, 0x8b, 0x0e,
	0x24, 0xa1, 0xb0, 0xc2, 0x7c, 0x5f, 0x4e, 0xa2, 0x94, 0x5a, 0x2d, 0xab, 0x53, 0xf1, 0xf2, 0x7f,
	0xc9, 0x06, 0x54, 0x74, 0xeb, 0x41, 0xc4, 0x42, 0x4e, 0x97, 0xb0, 0x56, 0xd6, 0xc0, 0x73, 0x16,
	0x72, 0xf2, 0x3f, 0x40, 0xc0, 0x54, 0x3a, 0xf0, 0xb5, 0x11, 0x5d, 0x6e, 0x59, 0x1d, 0xdb, 0xab,
	0x68, 0x04, 0x9d, 0xdb, 0xfb, 0x50, 0xde, 0xe5, 0x49, 0xd6, 0xa1, 0x09, 0x55, 0x79, 0x1c, 0xf1,
	0x64, 0x90, 0xc8, 0x80, 0x2b, 0x6a, 0xb5, 0x96, 0x3b, 0xb6, 0x07, 0x08, 0x79, 0x1a, 0x21, 0xb7,
	0x61, 0x35, 0x23, 0x98, 0xce, 0x8a, 0x2e, 0xb5, 0x96, 0x3b, 0x15, 0xaf, 0x8e, 0xe8, 0x13, 0x03,
	0x6e, 0xd9, 0xdf, 0x3e, 0x36, 0xad, 0x76, 0x0c, 0xb5, 0xd7, 0x5c, 0x8c, 0x0f, 0x53, 0x3e, 0xd2,
	0x6a, 0x42, 0xc0, 0xd6, 0xbe, 0x78, 0x79, 0xdb, 0xc3, 0x33, 0x79, 0x0a, 0xa5, 0x63, 0xe4, 0x64,
	0xd7, 0xee, 0x3a, 0xa7, 0xe7, 0xcd, 0xc2, 0x97, 0xf3, 0xe6, 0x9d, 0xb1, 0x48, 0x0f, 0x27, 0x43,
	0xc7, 0x97, 0xa1, 0xeb, 0x4b, 0x15, 0x4a, 0x65, 0xfe, 0xdc, 0x57, 0xa3, 0x23, 0x37, 0x9d, 0xc6,
	0x5c, 0x39, 0xdb, 0xdc, 0xf7, 0x8c, 0xda, 0x74, 0x9c, 0xc2, 0x5f, 0x79, 0x47, 0x73, 0x97, 0x5f,
	0x84, 0xf6, 0x67, 0x5b, 0x7f, 0xb0, 0xe0, 0xef, 0xbc, 0xf7, 0x2c, 0xcf, 0x87, 0x50, 0xbc, 0x4a,
	0xb2, 0xba, 0xb9, 0xe1, 0x2c, 0x2c, 0x85, 0x33, 0x9f, 0x4e, 0xd7, 0xd6, 0xed, 0xbd, 0x8c, 0x4f,
	0x1e, 0x43, 0x79, 0x21, 0xe1, 0xea, 0x66, 0xe3, 0x1a, 0xad, 0xf9, 0x9d, 0x46, 0x3e, 0x53, 0x99,
	0x5b, 0x7d, 0x2a, 0x42, 0x6d, 0xcf, 0x48, 0x76, 0xa5, 0x0c, 0xf4, 0x0c, 0x70, 0x49, 0xb2, 0x2c,
	0xf0, 0xac, 0xa7, 0x8e, 0xbb, 0x31, 0x50, 0x29, 0x4b, 0xb2, 0x34, 0x6c, 0x0f, 0x10, 0xda, 0xd3,
	0x88, 0x5e, 0xaf, 0x8c, 0xc0, 0xa3, 0x91, 0x59, 0xa0, 0x32, 0x02, 0xfd, 0x68, 0x44, 0x6e, 0x41,
	0xcd, 0x14, 0x4f, 0x62, 0x91, 0x4c, 0xa9, 0x8d, 0xf5, 0xcc, 0xb1, 0x8f, 0x10, 0xd9, 0x87, 0x62,
	0xc2, 0x52, 0xae, 0x68, 0x51, 0x2f, 0x4b, 0xb7, 0x6b, 0x82, 0xbe, 0x77, 0xb3, 0xa0, 0x7b, 0x52,
	0x44, 0xdf, 0xcf, 0x9b, 0xb5, 0x29, 0x0b, 0x83, 0xad, 0x36, 0x1a, 0xb5, 0xbd, 0xcc, 0x90, 0xbc,
	0x80, 0xea, 0x3b, 0x99, 0xf2, 0xc1, 0xdb, 0x89, 0x4c, 0x26, 0x21, 0x2d, 0xfd, 0xd6, 0x20, 0x41,
	0x5b, 0xbc, 0x44, 0x07, 0x9d, 0x05, 0x1a, 0xc6, 0x3c, 0x11, 0x72, 0x44, 0x57, 0xb2, 0x2c, 0x34,
	0xb4, 0x8b, 0x88, 0xfe, 0x02, 0x90, 0xc0, 0x23, 0xe6, 0xa7, 0x21, 0x8f, 0x52, 0x5a, 0x46, 0x4e,
	0x5d, 0xa3, 0xfd, 0x1c, 0x24, 0x2e, 0x94, 0xf0, 0x93, 0x50, 0xb4, 0xd2, 0xb2, 0x3a, 0xd5, 0xcd,
	0xb5, 0x9f, 0xc6, 0x97, 0xaf, 0x88, 0x67, 0x68, 0xa4, 0x0f, 0xf5, 0x21, 0x8f, 0xf8, 0x81, 0xf0,
	0x05, 0x4b, 0x04, 0x57, 0x14, 0x50, 0xd7, 0xbc, 0x66, 0xec, 0x33, 0xfd, 0xa2, 0x8a, 0xec, 0x40,
	0x79, 0xc8, 0x02, 0x16, 0xf9, 0x5c, 0xd1, 0x2a, 0xa6, 0xed, 0x9a, 0x34, 0xee, 0xde, 0x20, 0x0d,
	0x1d, 0xb5, 0x37, 0x33, 0xd0, 0xa3, 0x1d, 0x4d, 0x23, 0x16, 0x0a, 0x7f, 0xa0, 0xe3, 0xa6, 0xb5,
	0x96, 0xd5, 0x29, 0x7b, 0x55, 0x83, 0x79, 0x2c, 0xe5, 0xc4, 0x81, 0x7f, 0xe7, 0x29, 0x79, 0x6e,
	0x75, 0xcc, 0xe4, 0x9f, 0x39, 0xa6, 0x89, 0xef, 0x11, 0x6c, 0xe0, 0x63, 0xb4, 0x20, 0xf2, 0x59,
	0xe0, 0x0f, 0xf4, 0x83, 0x48, 0x57, 0x51, 0xb7, 0xa6, 0x29, 0xdb, 0x57, 0xda, 0x1e, 0x0b, 0xfc,
	0x57, 0x22, 0xe4, 0xdd, 0xed, 0xd3, 0x8b, 0x86, 0x75, 0x76, 0xd1, 0xb0, 0xbe, 0x5e, 0x34, 0xac,
	0xf7, 0x97, 0x8d, 0xc2, 0xd9, 0x65, 0xa3, 0xf0, 0xf9, 0xb2, 0x51, 0x78, 0x33, 0xbf, 0x4b, 0x3b,
	0x22, 0x61, 0x3d, 0x99, 0x70, 0x57, 0xf1, 0x23, 0x26, 0xdc, 0x93, 0xab, 0xf7, 0x19, 0x7f, 0xe5,
	0xb0, 0x84, 0x6f, 0xeb, 0x83, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x92, 0x8e, 0xa2, 0x88, 0xbd,
	0x05, 0x00, 0x00,
}

func (this *PermInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PermInfo)
	if !ok {
		that2, ok := that.(PermInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.OwnerRoles) != len(that1.OwnerRoles) {
		return false
	}
	for i := range this.OwnerRoles {
		if this.OwnerRoles[i] != that1.OwnerRoles[i] {
			return false
		}
	}
	if len(this.OwnerAccounts) != len(that1.OwnerAccounts) {
		return false
	}
	for i := range this.OwnerAccounts {
		if this.OwnerAccounts[i] != that1.OwnerAccounts[i] {
			return false
		}
	}
	return true
}
func (this *WeightedRole) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*WeightedRole)
	if !ok {
		that2, ok := that.(WeightedRole)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Role != that1.Role {
		return false
	}
	if !this.Weight.Equal(that1.Weight) {
		return false
	}
	return true
}
func (this *WeightedAccount) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*WeightedAccount)
	if !ok {
		that2, ok := that.(WeightedAccount)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Account != that1.Account {
		return false
	}
	if !this.Weight.Equal(that1.Weight) {
		return false
	}
	return true
}
func (this *WeightedPermInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*WeightedPermInfo)
	if !ok {
		that2, ok := that.(WeightedPermInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Roles) != len(that1.Roles) {
		return false
	}
	for i := range this.Roles {
		if !this.Roles[i].Equal(&that1.Roles[i]) {
			return false
		}
	}
	if len(this.Accounts) != len(that1.Accounts) {
		return false
	}
	for i := range this.Accounts {
		if !this.Accounts[i].Equal(&that1.Accounts[i]) {
			return false
		}
	}
	return true
}
func (m *ClaimInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClaimInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClaimInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastClaim != 0 {
		i = encodeVarintPool(dAtA, i, uint64(m.LastClaim))
		i--
		dAtA[i] = 0x18
	}
	if len(m.PoolName) > 0 {
		i -= len(m.PoolName)
		copy(dAtA[i:], m.PoolName)
		i = encodeVarintPool(dAtA, i, uint64(len(m.PoolName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintPool(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PermInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PermInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PermInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OwnerAccounts) > 0 {
		for iNdEx := len(m.OwnerAccounts) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.OwnerAccounts[iNdEx])
			copy(dAtA[i:], m.OwnerAccounts[iNdEx])
			i = encodeVarintPool(dAtA, i, uint64(len(m.OwnerAccounts[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.OwnerRoles) > 0 {
		dAtA2 := make([]byte, len(m.OwnerRoles)*10)
		var j1 int
		for _, num := range m.OwnerRoles {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintPool(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *WeightedRole) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WeightedRole) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WeightedRole) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Weight.Size()
		i -= size
		if _, err := m.Weight.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintPool(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Role != 0 {
		i = encodeVarintPool(dAtA, i, uint64(m.Role))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *WeightedAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WeightedAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WeightedAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Weight.Size()
		i -= size
		if _, err := m.Weight.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintPool(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintPool(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *WeightedPermInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WeightedPermInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WeightedPermInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Accounts) > 0 {
		for iNdEx := len(m.Accounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Accounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPool(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Roles) > 0 {
		for iNdEx := len(m.Roles) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Roles[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPool(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *SpendingPool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SpendingPool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SpendingPool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastDynamicRateCalcTime != 0 {
		i = encodeVarintPool(dAtA, i, uint64(m.LastDynamicRateCalcTime))
		i--
		dAtA[i] = 0x70
	}
	if m.DynamicRatePeriod != 0 {
		i = encodeVarintPool(dAtA, i, uint64(m.DynamicRatePeriod))
		i--
		dAtA[i] = 0x68
	}
	if m.DynamicRate {
		i--
		if m.DynamicRate {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x60
	}
	if len(m.Balances) > 0 {
		for iNdEx := len(m.Balances) - 1; iNdEx >= 0; iNdEx-- {
			{
				size := m.Balances[iNdEx].Size()
				i -= size
				if _, err := m.Balances[iNdEx].MarshalTo(dAtA[i:]); err != nil {
					return 0, err
				}
				i = encodeVarintPool(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if m.Beneficiaries != nil {
		{
			size, err := m.Beneficiaries.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPool(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x52
	}
	if m.Owners != nil {
		{
			size, err := m.Owners.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPool(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	if m.VoteEnactment != 0 {
		i = encodeVarintPool(dAtA, i, uint64(m.VoteEnactment))
		i--
		dAtA[i] = 0x40
	}
	if m.VotePeriod != 0 {
		i = encodeVarintPool(dAtA, i, uint64(m.VotePeriod))
		i--
		dAtA[i] = 0x38
	}
	{
		size := m.VoteQuorum.Size()
		i -= size
		if _, err := m.VoteQuorum.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintPool(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.Rates) > 0 {
		for iNdEx := len(m.Rates) - 1; iNdEx >= 0; iNdEx-- {
			{
				size := m.Rates[iNdEx].Size()
				i -= size
				if _, err := m.Rates[iNdEx].MarshalTo(dAtA[i:]); err != nil {
					return 0, err
				}
				i = encodeVarintPool(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.ClaimExpiry != 0 {
		i = encodeVarintPool(dAtA, i, uint64(m.ClaimExpiry))
		i--
		dAtA[i] = 0x20
	}
	if m.ClaimEnd != 0 {
		i = encodeVarintPool(dAtA, i, uint64(m.ClaimEnd))
		i--
		dAtA[i] = 0x18
	}
	if m.ClaimStart != 0 {
		i = encodeVarintPool(dAtA, i, uint64(m.ClaimStart))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintPool(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPool(dAtA []byte, offset int, v uint64) int {
	offset -= sovPool(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ClaimInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	l = len(m.PoolName)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	if m.LastClaim != 0 {
		n += 1 + sovPool(uint64(m.LastClaim))
	}
	return n
}

func (m *PermInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.OwnerRoles) > 0 {
		l = 0
		for _, e := range m.OwnerRoles {
			l += sovPool(uint64(e))
		}
		n += 1 + sovPool(uint64(l)) + l
	}
	if len(m.OwnerAccounts) > 0 {
		for _, s := range m.OwnerAccounts {
			l = len(s)
			n += 1 + l + sovPool(uint64(l))
		}
	}
	return n
}

func (m *WeightedRole) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Role != 0 {
		n += 1 + sovPool(uint64(m.Role))
	}
	l = m.Weight.Size()
	n += 1 + l + sovPool(uint64(l))
	return n
}

func (m *WeightedAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	l = m.Weight.Size()
	n += 1 + l + sovPool(uint64(l))
	return n
}

func (m *WeightedPermInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Roles) > 0 {
		for _, e := range m.Roles {
			l = e.Size()
			n += 1 + l + sovPool(uint64(l))
		}
	}
	if len(m.Accounts) > 0 {
		for _, e := range m.Accounts {
			l = e.Size()
			n += 1 + l + sovPool(uint64(l))
		}
	}
	return n
}

func (m *SpendingPool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	if m.ClaimStart != 0 {
		n += 1 + sovPool(uint64(m.ClaimStart))
	}
	if m.ClaimEnd != 0 {
		n += 1 + sovPool(uint64(m.ClaimEnd))
	}
	if m.ClaimExpiry != 0 {
		n += 1 + sovPool(uint64(m.ClaimExpiry))
	}
	if len(m.Rates) > 0 {
		for _, e := range m.Rates {
			l = e.Size()
			n += 1 + l + sovPool(uint64(l))
		}
	}
	l = m.VoteQuorum.Size()
	n += 1 + l + sovPool(uint64(l))
	if m.VotePeriod != 0 {
		n += 1 + sovPool(uint64(m.VotePeriod))
	}
	if m.VoteEnactment != 0 {
		n += 1 + sovPool(uint64(m.VoteEnactment))
	}
	if m.Owners != nil {
		l = m.Owners.Size()
		n += 1 + l + sovPool(uint64(l))
	}
	if m.Beneficiaries != nil {
		l = m.Beneficiaries.Size()
		n += 1 + l + sovPool(uint64(l))
	}
	if len(m.Balances) > 0 {
		for _, e := range m.Balances {
			l = e.Size()
			n += 1 + l + sovPool(uint64(l))
		}
	}
	if m.DynamicRate {
		n += 2
	}
	if m.DynamicRatePeriod != 0 {
		n += 1 + sovPool(uint64(m.DynamicRatePeriod))
	}
	if m.LastDynamicRateCalcTime != 0 {
		n += 1 + sovPool(uint64(m.LastDynamicRateCalcTime))
	}
	return n
}

func sovPool(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPool(x uint64) (n int) {
	return sovPool(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ClaimInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClaimInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClaimInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastClaim", wireType)
			}
			m.LastClaim = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastClaim |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PermInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PermInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PermInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPool
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.OwnerRoles = append(m.OwnerRoles, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPool
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthPool
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthPool
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.OwnerRoles) == 0 {
					m.OwnerRoles = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowPool
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.OwnerRoles = append(m.OwnerRoles, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerRoles", wireType)
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerAccounts", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerAccounts = append(m.OwnerAccounts, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WeightedRole) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WeightedRole: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WeightedRole: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Role", wireType)
			}
			m.Role = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Role |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weight", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Weight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WeightedAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WeightedAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WeightedAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weight", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Weight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WeightedPermInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WeightedPermInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WeightedPermInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Roles", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Roles = append(m.Roles, WeightedRole{})
			if err := m.Roles[len(m.Roles)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Accounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Accounts = append(m.Accounts, WeightedAccount{})
			if err := m.Accounts[len(m.Accounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SpendingPool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SpendingPool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SpendingPool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimStart", wireType)
			}
			m.ClaimStart = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClaimStart |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimEnd", wireType)
			}
			m.ClaimEnd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClaimEnd |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimExpiry", wireType)
			}
			m.ClaimExpiry = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClaimExpiry |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rates", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_cosmos_cosmos_sdk_types.DecCoin
			m.Rates = append(m.Rates, v)
			if err := m.Rates[len(m.Rates)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteQuorum", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VoteQuorum.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotePeriod", wireType)
			}
			m.VotePeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VotePeriod |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteEnactment", wireType)
			}
			m.VoteEnactment = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VoteEnactment |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owners", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Owners == nil {
				m.Owners = &PermInfo{}
			}
			if err := m.Owners.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Beneficiaries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Beneficiaries == nil {
				m.Beneficiaries = &WeightedPermInfo{}
			}
			if err := m.Beneficiaries.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balances", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_cosmos_cosmos_sdk_types.Coin
			m.Balances = append(m.Balances, v)
			if err := m.Balances[len(m.Balances)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DynamicRate", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DynamicRate = bool(v != 0)
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DynamicRatePeriod", wireType)
			}
			m.DynamicRatePeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DynamicRatePeriod |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastDynamicRateCalcTime", wireType)
			}
			m.LastDynamicRateCalcTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastDynamicRateCalcTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPool(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPool
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPool
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPool
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPool
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPool
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPool
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPool        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPool          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPool = fmt.Errorf("proto: unexpected end of group")
)
