// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kira/custody/query.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CustodyByAddressRequest struct {
	Addr github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=addr,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"addr,omitempty" yaml:"addr"`
}

func (m *CustodyByAddressRequest) Reset()         { *m = CustodyByAddressRequest{} }
func (m *CustodyByAddressRequest) String() string { return proto.CompactTextString(m) }
func (*CustodyByAddressRequest) ProtoMessage()    {}
func (*CustodyByAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c8d8c1227063c95, []int{0}
}
func (m *CustodyByAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CustodyByAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CustodyByAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CustodyByAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustodyByAddressRequest.Merge(m, src)
}
func (m *CustodyByAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *CustodyByAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CustodyByAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CustodyByAddressRequest proto.InternalMessageInfo

func (m *CustodyByAddressRequest) GetAddr() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Addr
	}
	return nil
}

type CustodyByAddressResponse struct {
	CustodySettings *CustodySettings `protobuf:"bytes,1,opt,name=custody_settings,json=custodySettings,proto3" json:"custody_settings,omitempty"`
}

func (m *CustodyByAddressResponse) Reset()         { *m = CustodyByAddressResponse{} }
func (m *CustodyByAddressResponse) String() string { return proto.CompactTextString(m) }
func (*CustodyByAddressResponse) ProtoMessage()    {}
func (*CustodyByAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c8d8c1227063c95, []int{1}
}
func (m *CustodyByAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CustodyByAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CustodyByAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CustodyByAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustodyByAddressResponse.Merge(m, src)
}
func (m *CustodyByAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *CustodyByAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CustodyByAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CustodyByAddressResponse proto.InternalMessageInfo

func (m *CustodyByAddressResponse) GetCustodySettings() *CustodySettings {
	if m != nil {
		return m.CustodySettings
	}
	return nil
}

type CustodyWhiteListByAddressRequest struct {
	Addr github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=addr,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"addr,omitempty" yaml:"addr"`
}

func (m *CustodyWhiteListByAddressRequest) Reset()         { *m = CustodyWhiteListByAddressRequest{} }
func (m *CustodyWhiteListByAddressRequest) String() string { return proto.CompactTextString(m) }
func (*CustodyWhiteListByAddressRequest) ProtoMessage()    {}
func (*CustodyWhiteListByAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c8d8c1227063c95, []int{2}
}
func (m *CustodyWhiteListByAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CustodyWhiteListByAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CustodyWhiteListByAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CustodyWhiteListByAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustodyWhiteListByAddressRequest.Merge(m, src)
}
func (m *CustodyWhiteListByAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *CustodyWhiteListByAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CustodyWhiteListByAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CustodyWhiteListByAddressRequest proto.InternalMessageInfo

func (m *CustodyWhiteListByAddressRequest) GetAddr() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Addr
	}
	return nil
}

type CustodyWhiteListByAddressResponse struct {
	CustodyWhiteList *CustodyWhiteList `protobuf:"bytes,1,opt,name=custody_white_list,json=custodyWhiteList,proto3" json:"custody_white_list,omitempty"`
}

func (m *CustodyWhiteListByAddressResponse) Reset()         { *m = CustodyWhiteListByAddressResponse{} }
func (m *CustodyWhiteListByAddressResponse) String() string { return proto.CompactTextString(m) }
func (*CustodyWhiteListByAddressResponse) ProtoMessage()    {}
func (*CustodyWhiteListByAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c8d8c1227063c95, []int{3}
}
func (m *CustodyWhiteListByAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CustodyWhiteListByAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CustodyWhiteListByAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CustodyWhiteListByAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustodyWhiteListByAddressResponse.Merge(m, src)
}
func (m *CustodyWhiteListByAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *CustodyWhiteListByAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CustodyWhiteListByAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CustodyWhiteListByAddressResponse proto.InternalMessageInfo

func (m *CustodyWhiteListByAddressResponse) GetCustodyWhiteList() *CustodyWhiteList {
	if m != nil {
		return m.CustodyWhiteList
	}
	return nil
}

type CustodyLimitsByAddressRequest struct {
	Addr github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=addr,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"addr,omitempty" yaml:"addr"`
}

func (m *CustodyLimitsByAddressRequest) Reset()         { *m = CustodyLimitsByAddressRequest{} }
func (m *CustodyLimitsByAddressRequest) String() string { return proto.CompactTextString(m) }
func (*CustodyLimitsByAddressRequest) ProtoMessage()    {}
func (*CustodyLimitsByAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c8d8c1227063c95, []int{4}
}
func (m *CustodyLimitsByAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CustodyLimitsByAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CustodyLimitsByAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CustodyLimitsByAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustodyLimitsByAddressRequest.Merge(m, src)
}
func (m *CustodyLimitsByAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *CustodyLimitsByAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CustodyLimitsByAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CustodyLimitsByAddressRequest proto.InternalMessageInfo

func (m *CustodyLimitsByAddressRequest) GetAddr() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Addr
	}
	return nil
}

type CustodyLimitsByAddressResponse struct {
	CustodyLimits *CustodyLimits `protobuf:"bytes,1,opt,name=custody_limits,json=custodyLimits,proto3" json:"custody_limits,omitempty"`
}

func (m *CustodyLimitsByAddressResponse) Reset()         { *m = CustodyLimitsByAddressResponse{} }
func (m *CustodyLimitsByAddressResponse) String() string { return proto.CompactTextString(m) }
func (*CustodyLimitsByAddressResponse) ProtoMessage()    {}
func (*CustodyLimitsByAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c8d8c1227063c95, []int{5}
}
func (m *CustodyLimitsByAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CustodyLimitsByAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CustodyLimitsByAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CustodyLimitsByAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustodyLimitsByAddressResponse.Merge(m, src)
}
func (m *CustodyLimitsByAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *CustodyLimitsByAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CustodyLimitsByAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CustodyLimitsByAddressResponse proto.InternalMessageInfo

func (m *CustodyLimitsByAddressResponse) GetCustodyLimits() *CustodyLimits {
	if m != nil {
		return m.CustodyLimits
	}
	return nil
}

type CustodyLimitsStatusByAddressRequest struct {
	Addr github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=addr,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"addr,omitempty" yaml:"addr"`
}

func (m *CustodyLimitsStatusByAddressRequest) Reset()         { *m = CustodyLimitsStatusByAddressRequest{} }
func (m *CustodyLimitsStatusByAddressRequest) String() string { return proto.CompactTextString(m) }
func (*CustodyLimitsStatusByAddressRequest) ProtoMessage()    {}
func (*CustodyLimitsStatusByAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c8d8c1227063c95, []int{6}
}
func (m *CustodyLimitsStatusByAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CustodyLimitsStatusByAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CustodyLimitsStatusByAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CustodyLimitsStatusByAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustodyLimitsStatusByAddressRequest.Merge(m, src)
}
func (m *CustodyLimitsStatusByAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *CustodyLimitsStatusByAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CustodyLimitsStatusByAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CustodyLimitsStatusByAddressRequest proto.InternalMessageInfo

func (m *CustodyLimitsStatusByAddressRequest) GetAddr() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Addr
	}
	return nil
}

type CustodyLimitsStatusByAddressResponse struct {
	CustodyStatuses *CustodyStatuses `protobuf:"bytes,1,opt,name=custody_statuses,json=custodyStatuses,proto3" json:"custody_statuses,omitempty"`
}

func (m *CustodyLimitsStatusByAddressResponse) Reset()         { *m = CustodyLimitsStatusByAddressResponse{} }
func (m *CustodyLimitsStatusByAddressResponse) String() string { return proto.CompactTextString(m) }
func (*CustodyLimitsStatusByAddressResponse) ProtoMessage()    {}
func (*CustodyLimitsStatusByAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c8d8c1227063c95, []int{7}
}
func (m *CustodyLimitsStatusByAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CustodyLimitsStatusByAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CustodyLimitsStatusByAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CustodyLimitsStatusByAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustodyLimitsStatusByAddressResponse.Merge(m, src)
}
func (m *CustodyLimitsStatusByAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *CustodyLimitsStatusByAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CustodyLimitsStatusByAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CustodyLimitsStatusByAddressResponse proto.InternalMessageInfo

func (m *CustodyLimitsStatusByAddressResponse) GetCustodyStatuses() *CustodyStatuses {
	if m != nil {
		return m.CustodyStatuses
	}
	return nil
}

func init() {
	proto.RegisterType((*CustodyByAddressRequest)(nil), "kira.custody.CustodyByAddressRequest")
	proto.RegisterType((*CustodyByAddressResponse)(nil), "kira.custody.CustodyByAddressResponse")
	proto.RegisterType((*CustodyWhiteListByAddressRequest)(nil), "kira.custody.CustodyWhiteListByAddressRequest")
	proto.RegisterType((*CustodyWhiteListByAddressResponse)(nil), "kira.custody.CustodyWhiteListByAddressResponse")
	proto.RegisterType((*CustodyLimitsByAddressRequest)(nil), "kira.custody.CustodyLimitsByAddressRequest")
	proto.RegisterType((*CustodyLimitsByAddressResponse)(nil), "kira.custody.CustodyLimitsByAddressResponse")
	proto.RegisterType((*CustodyLimitsStatusByAddressRequest)(nil), "kira.custody.CustodyLimitsStatusByAddressRequest")
	proto.RegisterType((*CustodyLimitsStatusByAddressResponse)(nil), "kira.custody.CustodyLimitsStatusByAddressResponse")
}

func init() { proto.RegisterFile("kira/custody/query.proto", fileDescriptor_6c8d8c1227063c95) }

var fileDescriptor_6c8d8c1227063c95 = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0x8e, 0x11, 0x65, 0xb8, 0x16, 0xa8, 0x4e, 0x08, 0x42, 0x68, 0xdd, 0xe2, 0x12, 0x4a, 0x69,
	0xe3, 0x13, 0x61, 0x63, 0xa2, 0xc9, 0x82, 0x44, 0x16, 0x52, 0x24, 0x24, 0x96, 0xca, 0xb5, 0x4f,
	0xee, 0x29, 0x89, 0xcf, 0xf1, 0x9d, 0x45, 0xad, 0x8a, 0x85, 0x5f, 0x50, 0x89, 0x3f, 0xc0, 0xca,
	0xc0, 0x0f, 0xe0, 0x1f, 0x30, 0x56, 0x62, 0x61, 0xaa, 0x50, 0xc2, 0x2f, 0x60, 0x64, 0x42, 0x3e,
	0x3f, 0xa7, 0x49, 0x73, 0x75, 0xdb, 0x25, 0x93, 0x93, 0xf7, 0xbe, 0xbc, 0xf7, 0x7d, 0x2f, 0xdf,
	0x97, 0xa0, 0x72, 0x87, 0x45, 0x0e, 0x71, 0x63, 0x21, 0xb9, 0x97, 0x90, 0x7e, 0x4c, 0xa3, 0xc4,
	0x0e, 0x23, 0x2e, 0x39, 0x5e, 0x48, 0x3b, 0x36, 0x74, 0x2a, 0x77, 0x7c, 0xee, 0x73, 0xd5, 0x20,
	0xe9, 0xab, 0x0c, 0x53, 0x59, 0xf2, 0x39, 0xf7, 0xbb, 0x94, 0x38, 0x21, 0x23, 0x4e, 0x10, 0x70,
	0xe9, 0x48, 0xc6, 0x03, 0x01, 0xdd, 0xca, 0xc4, 0x6c, 0x78, 0x66, 0x3d, 0x8b, 0xa3, 0x7b, 0xcd,
	0xac, 0xd0, 0x48, 0xb6, 0x3d, 0x2f, 0xa2, 0x42, 0xb4, 0x69, 0x3f, 0xa6, 0x42, 0xe2, 0xb7, 0xe8,
	0xba, 0xe3, 0x79, 0x51, 0xd9, 0x58, 0x35, 0x9e, 0x2c, 0x34, 0x5e, 0xfe, 0x3d, 0x59, 0x99, 0x4f,
	0x9c, 0x5e, 0xf7, 0x85, 0x95, 0x56, 0xad, 0x7f, 0x27, 0x2b, 0x35, 0x9f, 0xc9, 0xfd, 0x78, 0xcf,
	0x76, 0x79, 0x8f, 0xb8, 0x5c, 0xf4, 0xb8, 0x80, 0x47, 0x4d, 0x78, 0x1d, 0x22, 0x93, 0x90, 0x0a,
	0x7b, 0xdb, 0x75, 0xf3, 0xb1, 0x6a, 0x9a, 0xe5, 0xa1, 0xf2, 0xf4, 0x42, 0x11, 0xf2, 0x40, 0x50,
	0xfc, 0x0a, 0x2d, 0x02, 0xbb, 0x5d, 0x41, 0xa5, 0x64, 0x81, 0x2f, 0xd4, 0xf6, 0xf9, 0xfa, 0xb2,
	0x3d, 0x7e, 0x05, 0x1b, 0x26, 0xec, 0x00, 0xa8, 0x7d, 0xdb, 0x9d, 0x2c, 0x58, 0x07, 0x68, 0x15,
	0x30, 0xef, 0xf6, 0x99, 0xa4, 0x2d, 0x26, 0xe4, 0x8c, 0xf4, 0xf5, 0xd1, 0xc3, 0x82, 0xcd, 0x20,
	0xb4, 0x85, 0x70, 0x2e, 0xf4, 0x43, 0x8a, 0xda, 0xed, 0x32, 0x21, 0x41, 0xaa, 0xa9, 0x95, 0x3a,
	0x1a, 0xd6, 0xce, 0x4f, 0x34, 0xaa, 0x58, 0x31, 0x5a, 0x06, 0x54, 0x8b, 0xf5, 0x98, 0x14, 0x33,
	0xfb, 0x26, 0xcd, 0xf3, 0xd6, 0x82, 0xcc, 0x06, 0xba, 0x95, 0xcb, 0xec, 0x2a, 0x08, 0x48, 0x7c,
	0xa0, 0x95, 0x98, 0x4d, 0x69, 0xdf, 0x74, 0xc7, 0xdf, 0x5a, 0x87, 0x68, 0x6d, 0xa2, 0xbf, 0x23,
	0x1d, 0x19, 0xcf, 0x4a, 0x62, 0x88, 0x1e, 0x15, 0x2f, 0xd7, 0x18, 0x57, 0x41, 0xe8, 0x05, 0xc6,
	0x05, 0xd0, 0xa9, 0x71, 0xa1, 0x50, 0xff, 0x3a, 0x87, 0xe6, 0xde, 0xa4, 0xe9, 0xc7, 0x47, 0x06,
	0x5a, 0x3c, 0x9b, 0x14, 0x5c, 0xd5, 0x8e, 0x3b, 0x7b, 0x8d, 0xca, 0xe3, 0x8b, 0x60, 0x19, 0x6f,
	0xab, 0xf6, 0xe9, 0xe7, 0x9f, 0xcf, 0xd7, 0xd6, 0x71, 0x95, 0xe8, 0x7e, 0x22, 0x46, 0x21, 0x24,
	0x87, 0xe9, 0x35, 0x3e, 0xe2, 0x6f, 0x06, 0xba, 0x7f, 0xae, 0xb9, 0xb1, 0x5d, 0x6c, 0xdc, 0x29,
	0x92, 0xe4, 0xd2, 0x78, 0x60, 0x4b, 0x14, 0xdb, 0x0d, 0xbc, 0xae, 0x67, 0x7b, 0x9a, 0xa4, 0x9c,
	0xef, 0x17, 0x03, 0xdd, 0xd5, 0x5b, 0x14, 0x6f, 0x16, 0x58, 0x70, 0x8a, 0xe9, 0xd6, 0xe5, 0xc0,
	0x40, 0x73, 0x53, 0xd1, 0xac, 0xe2, 0x35, 0x3d, 0xcd, 0x2c, 0x09, 0x39, 0xc5, 0xef, 0x06, 0x5a,
	0x2a, 0xb2, 0x18, 0x7e, 0x56, 0xb0, 0x5b, 0x9f, 0x85, 0x4a, 0xfd, 0x2a, 0x1f, 0x01, 0xd2, 0x75,
	0x45, 0x7a, 0x0b, 0x3f, 0x2d, 0x22, 0x0d, 0xe6, 0x06, 0xee, 0x8d, 0xe6, 0x8f, 0x81, 0x69, 0x1c,
	0x0f, 0x4c, 0xe3, 0xf7, 0xc0, 0x34, 0x8e, 0x86, 0x66, 0xe9, 0x78, 0x68, 0x96, 0x7e, 0x0d, 0xcd,
	0xd2, 0xfb, 0x8d, 0xb1, 0xb0, 0xbd, 0x66, 0x91, 0xd3, 0xe4, 0x11, 0x25, 0x82, 0x76, 0x1c, 0x46,
	0x0e, 0x46, 0xb3, 0x55, 0xe6, 0xf6, 0x6e, 0xa8, 0xff, 0xa1, 0xe7, 0xff, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x60, 0x8c, 0x7d, 0xce, 0x01, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	CustodyByAddress(ctx context.Context, in *CustodyByAddressRequest, opts ...grpc.CallOption) (*CustodyByAddressResponse, error)
	CustodyWhiteListByAddress(ctx context.Context, in *CustodyWhiteListByAddressRequest, opts ...grpc.CallOption) (*CustodyWhiteListByAddressResponse, error)
	CustodyLimitsByAddress(ctx context.Context, in *CustodyLimitsByAddressRequest, opts ...grpc.CallOption) (*CustodyLimitsByAddressResponse, error)
	CustodyLimitsStatusByAddress(ctx context.Context, in *CustodyLimitsStatusByAddressRequest, opts ...grpc.CallOption) (*CustodyLimitsStatusByAddressResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) CustodyByAddress(ctx context.Context, in *CustodyByAddressRequest, opts ...grpc.CallOption) (*CustodyByAddressResponse, error) {
	out := new(CustodyByAddressResponse)
	err := c.cc.Invoke(ctx, "/kira.custody.Query/CustodyByAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CustodyWhiteListByAddress(ctx context.Context, in *CustodyWhiteListByAddressRequest, opts ...grpc.CallOption) (*CustodyWhiteListByAddressResponse, error) {
	out := new(CustodyWhiteListByAddressResponse)
	err := c.cc.Invoke(ctx, "/kira.custody.Query/CustodyWhiteListByAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CustodyLimitsByAddress(ctx context.Context, in *CustodyLimitsByAddressRequest, opts ...grpc.CallOption) (*CustodyLimitsByAddressResponse, error) {
	out := new(CustodyLimitsByAddressResponse)
	err := c.cc.Invoke(ctx, "/kira.custody.Query/CustodyLimitsByAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CustodyLimitsStatusByAddress(ctx context.Context, in *CustodyLimitsStatusByAddressRequest, opts ...grpc.CallOption) (*CustodyLimitsStatusByAddressResponse, error) {
	out := new(CustodyLimitsStatusByAddressResponse)
	err := c.cc.Invoke(ctx, "/kira.custody.Query/CustodyLimitsStatusByAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	CustodyByAddress(context.Context, *CustodyByAddressRequest) (*CustodyByAddressResponse, error)
	CustodyWhiteListByAddress(context.Context, *CustodyWhiteListByAddressRequest) (*CustodyWhiteListByAddressResponse, error)
	CustodyLimitsByAddress(context.Context, *CustodyLimitsByAddressRequest) (*CustodyLimitsByAddressResponse, error)
	CustodyLimitsStatusByAddress(context.Context, *CustodyLimitsStatusByAddressRequest) (*CustodyLimitsStatusByAddressResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) CustodyByAddress(ctx context.Context, req *CustodyByAddressRequest) (*CustodyByAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustodyByAddress not implemented")
}
func (*UnimplementedQueryServer) CustodyWhiteListByAddress(ctx context.Context, req *CustodyWhiteListByAddressRequest) (*CustodyWhiteListByAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustodyWhiteListByAddress not implemented")
}
func (*UnimplementedQueryServer) CustodyLimitsByAddress(ctx context.Context, req *CustodyLimitsByAddressRequest) (*CustodyLimitsByAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustodyLimitsByAddress not implemented")
}
func (*UnimplementedQueryServer) CustodyLimitsStatusByAddress(ctx context.Context, req *CustodyLimitsStatusByAddressRequest) (*CustodyLimitsStatusByAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustodyLimitsStatusByAddress not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_CustodyByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustodyByAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CustodyByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kira.custody.Query/CustodyByAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CustodyByAddress(ctx, req.(*CustodyByAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CustodyWhiteListByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustodyWhiteListByAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CustodyWhiteListByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kira.custody.Query/CustodyWhiteListByAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CustodyWhiteListByAddress(ctx, req.(*CustodyWhiteListByAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CustodyLimitsByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustodyLimitsByAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CustodyLimitsByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kira.custody.Query/CustodyLimitsByAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CustodyLimitsByAddress(ctx, req.(*CustodyLimitsByAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CustodyLimitsStatusByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustodyLimitsStatusByAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CustodyLimitsStatusByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kira.custody.Query/CustodyLimitsStatusByAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CustodyLimitsStatusByAddress(ctx, req.(*CustodyLimitsStatusByAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kira.custody.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CustodyByAddress",
			Handler:    _Query_CustodyByAddress_Handler,
		},
		{
			MethodName: "CustodyWhiteListByAddress",
			Handler:    _Query_CustodyWhiteListByAddress_Handler,
		},
		{
			MethodName: "CustodyLimitsByAddress",
			Handler:    _Query_CustodyLimitsByAddress_Handler,
		},
		{
			MethodName: "CustodyLimitsStatusByAddress",
			Handler:    _Query_CustodyLimitsStatusByAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kira/custody/query.proto",
}

func (m *CustodyByAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CustodyByAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CustodyByAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Addr) > 0 {
		i -= len(m.Addr)
		copy(dAtA[i:], m.Addr)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Addr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CustodyByAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CustodyByAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CustodyByAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CustodySettings != nil {
		{
			size, err := m.CustodySettings.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CustodyWhiteListByAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CustodyWhiteListByAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CustodyWhiteListByAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Addr) > 0 {
		i -= len(m.Addr)
		copy(dAtA[i:], m.Addr)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Addr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CustodyWhiteListByAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CustodyWhiteListByAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CustodyWhiteListByAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CustodyWhiteList != nil {
		{
			size, err := m.CustodyWhiteList.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CustodyLimitsByAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CustodyLimitsByAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CustodyLimitsByAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Addr) > 0 {
		i -= len(m.Addr)
		copy(dAtA[i:], m.Addr)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Addr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CustodyLimitsByAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CustodyLimitsByAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CustodyLimitsByAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CustodyLimits != nil {
		{
			size, err := m.CustodyLimits.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CustodyLimitsStatusByAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CustodyLimitsStatusByAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CustodyLimitsStatusByAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Addr) > 0 {
		i -= len(m.Addr)
		copy(dAtA[i:], m.Addr)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Addr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CustodyLimitsStatusByAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CustodyLimitsStatusByAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CustodyLimitsStatusByAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CustodyStatuses != nil {
		{
			size, err := m.CustodyStatuses.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CustodyByAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Addr)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *CustodyByAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CustodySettings != nil {
		l = m.CustodySettings.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *CustodyWhiteListByAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Addr)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *CustodyWhiteListByAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CustodyWhiteList != nil {
		l = m.CustodyWhiteList.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *CustodyLimitsByAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Addr)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *CustodyLimitsByAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CustodyLimits != nil {
		l = m.CustodyLimits.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *CustodyLimitsStatusByAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Addr)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *CustodyLimitsStatusByAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CustodyStatuses != nil {
		l = m.CustodyStatuses.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CustodyByAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CustodyByAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CustodyByAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addr", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addr = append(m.Addr[:0], dAtA[iNdEx:postIndex]...)
			if m.Addr == nil {
				m.Addr = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CustodyByAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CustodyByAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CustodyByAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CustodySettings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CustodySettings == nil {
				m.CustodySettings = &CustodySettings{}
			}
			if err := m.CustodySettings.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CustodyWhiteListByAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CustodyWhiteListByAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CustodyWhiteListByAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addr", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addr = append(m.Addr[:0], dAtA[iNdEx:postIndex]...)
			if m.Addr == nil {
				m.Addr = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CustodyWhiteListByAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CustodyWhiteListByAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CustodyWhiteListByAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CustodyWhiteList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CustodyWhiteList == nil {
				m.CustodyWhiteList = &CustodyWhiteList{}
			}
			if err := m.CustodyWhiteList.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CustodyLimitsByAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CustodyLimitsByAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CustodyLimitsByAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addr", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addr = append(m.Addr[:0], dAtA[iNdEx:postIndex]...)
			if m.Addr == nil {
				m.Addr = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CustodyLimitsByAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CustodyLimitsByAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CustodyLimitsByAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CustodyLimits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CustodyLimits == nil {
				m.CustodyLimits = &CustodyLimits{}
			}
			if err := m.CustodyLimits.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CustodyLimitsStatusByAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CustodyLimitsStatusByAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CustodyLimitsStatusByAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addr", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addr = append(m.Addr[:0], dAtA[iNdEx:postIndex]...)
			if m.Addr == nil {
				m.Addr = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CustodyLimitsStatusByAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CustodyLimitsStatusByAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CustodyLimitsStatusByAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CustodyStatuses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CustodyStatuses == nil {
				m.CustodyStatuses = &CustodyStatuses{}
			}
			if err := m.CustodyStatuses.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
