name: Release Merged Hook

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  trigger-dispatch:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/v')
    runs-on: ubuntu-latest
    steps:
      - name: Extract Version from Branch Name
        id: version-extract
        run: echo "version=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
        shell: bash

      - name: Trigger Repository Dispatch Event
        env:
          VERSION: ${{ env.version }}
        run: |
          VERSION=${VERSION#"release/"} 
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          "https://api.github.com/repos/${{ secrets.DISPATCH_OWNER }}/${{ secrets.DISPATCH_REPO }}/dispatches" \
          -d "{\"event_type\":\"release_merged\", \"client_payload\": {\"version\":\"${VERSION}\"}}"

