name: Clean spam PRs

on:
  pull_request:
    branches: [ master, dev, latest, v*.*.*, feature/*, bugfix/* ]

jobs:
  # isolate signing & repo cloning from docker image
  setup:
    name: Verify PR validity
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      packages: write
      id-token: write
      pull-requests: write
    env:
      REF_BRANCH: ${{ github.event.pull_request.head.ref }}
      BASE_REF_BRANCH: ${{ github.base_ref }}
    steps:
          # ref.: https://github.com/actions/checkout, v3.0.0
          - name: Checkout repository
            uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
          # Branch name is also a version of the release
          # ref: https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
          - name: Extract branch name & release version
            shell: bash
            run: |
              echo "RELEASE_VER=$(grep -Fn -m 1 'Release: ' ./RELEASE.md | rev | cut -d ":" -f1 | rev | xargs | tr -dc '[:alnum:]\-\.' || echo '')" >> $GITHUB_ENV
              echo "SOURCE_BRANCH=$(echo ${{ env.REF_BRANCH }} | tr / -)" >> $GITHUB_ENV
              echo "DESTINATION_BRANCH=$(echo ${{ env.BASE_REF_BRANCH }} | tr / -)" >> $GITHUB_ENV
          - name: Print debug data before publishing
            run: |
              echo "Source branch name: ${{ env.SOURCE_BRANCH }}"
              echo "Destination branch name: ${{ env.DESTINATION_BRANCH }}"
          - name: Reject invalid PRs to master, dev or latest
            # ref.: https://github.com/dessant/repo-lockdown
            uses: dessant/repo-lockdown@0b093279a77b44bbc38e85089b5463dd06b4aea4
            if: |
              ( env.DESTINATION_BRANCH == 'master' || env.DESTINATION_BRANCH == 'dev' || env.DESTINATION_BRANCH == 'latest' ) &&
              ( !startsWith(env.SOURCE_BRANCH, 'v') && !contains(env.SOURCE_BRANCH, '.') )
            with:
              pr-labels: 'invalid'
              pr-comment: >
                This repository does not accept pull requests from non version branches
              close-pr: true
          - name: Reject invalid PRs to version branches that do NOT originate from feature/* or debug/*
            # ref.: https://github.com/dessant/repo-lockdown
            uses: dessant/repo-lockdown@0b093279a77b44bbc38e85089b5463dd06b4aea4
            if: |
              ( startsWith(env.DESTINATION_BRANCH, 'v') && contains(env.DESTINATION_BRANCH, '.') ) &&
              ( !startsWith(env.SOURCE_BRANCH, 'feature') && !startsWith(env.SOURCE_BRANCH, 'bugfix') )
            with:
              pr-labels: 'invalid'
              pr-comment: >
                This repository does not accept pull requests from feature/* & bugfix/* branches
              close-pr: true
          - name: Reject invalid PRs to version branches with invalid RELEASE files
            # ref.: https://github.com/dessant/repo-lockdown
            uses: dessant/repo-lockdown@0b093279a77b44bbc38e85089b5463dd06b4aea4
            if: |
              ( startsWith(env.DESTINATION_BRANCH, 'v') && contains(env.DESTINATION_BRANCH, '.') ) &&
              ( env.DESTINATION_BRANCH != env.RELEASE_VER )
            with:
              pr-labels: 'invalid'
              pr-comment: >
                The release version (${{ env.RELEASE_VER }}) in the ./RELEASE.md file does NOT match the branch name (${{ env.DESTINATION_BRANCH }})
              close-pr: false